# Netlify Secrets Configuration
# These are public environment variables that are safe to expose

[secrets]
  # Public Supabase configuration - these are meant to be public
  allow = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  ]