[build]
  command = "./scripts/netlify-build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  # Skip type checking and linting in production build if needed
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/"
  to = "/studio"
  status = 302
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"