# Netlify Secrets Configuration
# These environment variables are PUBLIC and safe to expose

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[secrets]
  # Skip scanning for public environment variables
  skip_secret_scanning = true
  
  # Alternatively, whitelist specific public variables
  allowed_secrets = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  ]