[build]
  command = "npm run build && rm -rf .next/cache"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.9.0"
  # Skip type checking and linting in production build if needed
  NEXT_TELEMETRY_DISABLED = "1"

# Secrets scanning configuration  
[build.processing.secrets]
  # Skip scanning as NEXT_PUBLIC_* vars are meant to be public
  skip = true

[[redirects]]
  from = "/"
  to = "/studio"
  status = 302
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"